### PR TITLE
Issue-2 First version of the example magnitude.json file

### PR DESCRIPTION
**Pull request by jpatton-USGS**
First version of the example magnitude.json file
* Values in this file were taken from either the database views for event 50003UWR, or a corresponding generated quakeml file to provide calculated values not stored in the hydra database schema.
* Hydra does not have anything corresponding to beachball-type, so I left it blank.
* Fixes usgs/hydra-web-display#2

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
Per the GeoJSON spec, a Feature must have a "geometry" member (which can be null).

http://geojson.org/geojson-spec.html#feature-objects

**Comment by jpatton-USGS** [comment]
I added the "geometry" member.  I set it to be a point, with the point value being the derived latitude/longitude/depth.  Does this make the corresponding members in properties redundant?  Or is this not the best way, and geometry should be null?

**Comment by jmfee-usgs** [comment]
I think it's okay as long as you aren't mixing derived/input data.  For moment tensor products (not in geojson format, but anyways...) we set latitude/longitude/depth to the input values, and store derived values as properties.

**Comment by jpatton-USGS** [comment]
Updated example to match endpoint output.

**Pull request merged**
